apiVersion: v1
kind: Service
metadata:
  name: py-pg
  namespace: dev
spec:
  selector:
    app: py-pg
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-pg
  namespace: dev
  labels:
    app: py-pg
spec:
  selector:
    matchLabels:
      app: py-pg
  template:
    metadata:
      labels:                                                                                                                                                                                                                               
        app: py-pg
    spec:
      containers:
      - name: py-pg
        image: zramos2/py-pg:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
