version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: pg
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  flask:
    build: .
    image: zramos2/scale-app
    container_name: scale
    ports:
      - 80:80
    depends_on:
      - postgres
volumes:
  dbdata:
